/*
 * The public surface of com.etendoerp.uikit.
 *
 * GENERATED by verify/gen-dts.mjs from the JSDoc in web/com.etendoerp.uikit/js/uikit.js.
 * Do not edit: gate G9 regenerates it and fails the build if this file disagrees with the
 * runtime. To change a signature, change the annotation next to the function.
 *
 * There is no module system in a Classic page: the runtime publishes one global, OB.UIKit,
 * and every name below is reached through it.
 */

declare namespace OB.UIKit {
  /** Already-escaped HTML. Only html`` and raw() produce one; nothing else should. */
  interface Raw {
    html: string;
    toString(): string;
  }

  /** The runtime's own version, for a view that needs to assert a minimum. */
  const version: string;

  /**
   * Escapes a value for HTML text or a quoted attribute. Null and undefined become the empty
   * string, so a missing field renders as nothing instead of the word "undefined".
   */
  function esc(value: unknown): string;

  /**
   * Wraps already-safe HTML. Idempotent, so passing a Raw through it is free and safe.
   */
  function raw(html: string | Raw): Raw;

  /**
   * Tagged template that escapes every interpolation. Arrays are joined with no separator, so
   * `html`<ul>${items.map(li)}</ul>`` works, and a raw() value passes through untouched.
   *
   * Returns a Raw, which is what makes composition work: the result of one html`` interpolated
   * into another is already-safe HTML and must not be escaped a second time. Do not `.join('')`
   * a list of results -- that flattens them back to a plain string, which the next html`` will
   * escape; interpolate the array itself instead.
   */
  function html(strings: string[], ...values: unknown[]): Raw;

  /**
   * Registers translated strings. Values come from AD_MESSAGE, never from source.
   */
  function labels(map: Record<string, string>): void;

  /**
   * The label for a key, or the key itself, which makes a missing AD_MESSAGE visible on screen.
   */
  function t(key: string): string;

  /**
   * Maps a logical datasource name to the action handler that answers it. Handlers are reached by
   * fully qualified class name; KernelServlet needs no AD row to publish one.
   */
  function datasource(name: string, spec: { action: string }): void;

  /**
   * GETs one datasource. The callback receives (error, data): exactly one of the two is set, and
   * a server-side error arrives as an Error rather than as data the caller might render.
   */
  function fetch(name: string, params: Record<string, unknown>, callback: (a: Error | null, b?: object) => void): void;

  /**
   * Injects a stylesheet once per key, so a redraw or a second tab cannot duplicate it.
   */
  function style(key: string, css: string): void;

  /**
   * A small state pill. An unknown state degrades to the neutral one rather than throwing.
   */
  function badge(text: unknown, state: 'ok' | 'risk' | 'bad' | 'flat'): Raw;

  /**
   * The pace rail: fill at `progress`, tick at `expected`, colour from the distance between them.
   * Not a progress bar -- a bar at 62% tells the reader nothing until they know what day it is.
   */
  function rail(progress: number, expected: number, state: 'ok' | 'risk' | 'bad' | 'flat'): Raw;

  /**
   * The score meter: ten cells for a 0.00-1.00 score, filled to `score`, with the cell holding
   * `target` outlined. Answers "will the commitment be met" without comparing two numbers.
   */
  function meter(score: number, target: number): Raw;

  /**
   * Confines n to [lo, hi].
   */
  function clamp(n: number, lo: number, hi: number): number;

  /**
   * Defines a Classic view that owns its own DOM subtree.
   *
   * Rendering is whole-region strings, and a region is written only when its string changed. That
   * is what keeps the filter bar from flickering when the user clicks a chip inside it.
   */
  function defineView(spec: {
    name: string;  // the view id, matching OBUIAPP_View_Impl.name and isc.<name>
    title?: string;  // label key for the tab title; falls back to the view id
    state: object;  // the initial state object; every key is yours
    data?: Record<string, string>;  // { alias: 'DatasourceName' }, fetched before the first render
    params?: (a: object) => Record<string, unknown>;  // (state) => request params; a change to these refetches
    regions?: string[];  // region names, in render order
    keepScroll?: string[];  // region names whose scrollTop survives a redraw
    render: (a: object, b: object) => Record<string, string | Raw>;  // (state, data) => { region: html }
    on?: Record<string, (a: object, b: Event, c: Element) => void>;  // { 'click [data-x]': handler }
  }): object;

}
